### ISSUE TITLE
Make Crown logo a png (attached)

### ISSUE THREAD

**Issue by jamesbirrellgray** [CJSCommonPlatform/ngGovUk#10]
![gov uk_logotype_crown](https://cloud.githubusercontent.com/assets/16034882/12981288/f3b70b96-d0d7-11e5-82ad-f25b1dcb23e6.png)

**Comment by jamesbirrellgray** [comment]
Where is this for?

**Comment by vygis** [comment]
Should this replace the following `PNG` that's already in place?
![gov uk_logotype_crown](http://cjscommonplatform.github.io/ngGovUk/assets/img/gov.uk_logotype_crown.png)
