### ISSUE TITLE
Register your account left hand menu

### ISSUE THREAD

**Issue by Javilete** [CJSCommonPlatform/ngGovUk#11]
Hello,
I have not been able to find the right styling for the left hand menu during the registration process. There are some tables but if we need to use any of those, I would like the confirmation. Can you please advice whether it is necessary to be created or we need to use existing components with some tweaking?
Find the image below:
![screen shot 2016-02-16 at 14 33 10](https://cloud.githubusercontent.com/assets/5079661/13079113/90105868-d4ba-11e5-9a78-c2929d61e9fe.png)

Thank you in advance.

**Comment by fabiotisci** [comment]
Hi Javier,

I'm not sure i understood you properly.
The left navigation menu is a independent directive included in ngGovUk.
You could override some styles using less if you need to change out
appearance.

Cheers

**Comment by azharulc** [comment]
This bit has now been created
