### ISSUE TITLE
New alert/notification style

### ISSUE THREAD

**Issue by mszygenda** [CJSCommonPlatform/ngGovUk#12]
I couldn't find notification/alert as in the design provided by Larry. Have a look at the screenshot

<img width="1122" alt="screen shot 2016-02-19 at 10 29 32" src="https://cloud.githubusercontent.com/assets/135435/13173152/ee6ded68-d6f3-11e5-973e-fd5329de535a.png">

**Comment by jamesbirrellgray** [comment]
At the moment, there isn't anyone that is dedicated to this project full time, and this project will grow, please feel free to create PRs and add these new components in yourself.

**Comment by vygis** [comment]
@mszygenda can you ping to discuss this?

**Comment by mszygenda** [comment]
Ok, thanks! For the time-being we implemented workaround with custom CSS for that screen. We'll update it in spare time.
