### ISSUE TITLE
Checkboxes / input tags

### ISSUE THREAD

**Issue by akwiatek** [CJSCommonPlatform/ngGovUk#13]
Example `input` tags in Checkboxes section are not closed at all, e.g.
```html
<label for="checkbox-1" class="checkbox block-background" ng-class="{selected: isChecked1}">
	<input id="checkbox-1" ng-model="isChecked1" value="waste-animal" type="checkbox">
	Waste from animal carcasses
</label>
```
That produces an invalid HTML page.

**Comment by akwiatek** [comment]
Example input tag usage: https://docs.angularjs.org/api/ng/directive/input

**Comment by vygis** [comment]
A non closing `<input>` element is valid HTML5.
The above link in the angular docs suggests not closing it:
```
    <label>
       User name:
       <input type="text" name="userName" ng-model="user.name" required>
    </label>
```
