### ISSUE TITLE
Components for IdAM Support Admin App

### ISSUE THREAD

**Issue by akwiatek** [CJSCommonPlatform/ngGovUk#15]
Please add style classes which allow us to create
* a header for a group of fields which is can be placed above a set of radio buttons,
* an input field with a label on the left side where there can be specified the field is optional.

<img width="771" src="https://cloud.githubusercontent.com/assets/16196861/13325708/da9d4d92-dbda-11e5-9c1f-241e2e95a7ed.png">

The screenshot has been provided by IdAM UX template _IdAM_MVP_support_admin_v6_FINAL.pdf_

**Comment by vygis** [comment]
@akwiatek I've created several classes to enable you to achieve this design:

have a look at this plunkr for suggested html:
[http://plnkr.co/edit/8pzoZ2?p=preview](http://plnkr.co/edit/8pzoZ2?p=preview)
