### ISSUE TITLE
Styling and classes improvements

### ISSUE THREAD

**Issue by Javilete** [CJSCommonPlatform/ngGovUk#16]
We would need the following components and classes in the style guide to be able to include them in IDAM:
1. Grey box to reflect digit numbers like the snapshot below:
![screen shot 2016-03-03 at 16 41 27](https://cloud.githubusercontent.com/assets/5079661/13501518/e52590c4-e15e-11e5-9b03-9730f61f49e8.png)
2. Read only menu to be able to reflect the step in which we are currently, grey tick and colour of the text like the snapshot below:
![screen shot 2016-03-03 at 16 43 16](https://cloud.githubusercontent.com/assets/5079661/13501558/0e81ca78-e15f-11e5-9d49-8d7724d38021.png)
3. Alignment between input boxes and links like the following:
![screen shot 2016-03-03 at 16 44 02](https://cloud.githubusercontent.com/assets/5079661/13501577/29076376-e15f-11e5-8bd1-49f8e7c364e4.png)

Thank you in advance.

**Comment by vygis** [comment]
@Javilete could you ping me on the MoJ slack when you're available (@vygintas)? I've started doing work on this project and I'd like to get a bit more context about your requirements.

**Comment by PanosParalakis** [comment]
I am working on 2.Read only menu

**Comment by PanosParalakis** [comment]
Resolved by PR #67 

- CSS Elements > Typography > Digit numbers confirmantion box 
- CSS Elements > Form Elements >  Input boxes & link alignement 
- UI Components > Progress List
