### ISSUE TITLE
Modal dialog positioning is off if loading ngGovUk styles on top of bootstrap css

### ISSUE THREAD

**Issue by nubz** [CJSCommonPlatform/ngGovUk#25]
The combination of bootstrap 3 and ngGovUk breaks positioning on modal dialogs - overriding the bootstrap declaration:

`.modal-dialog {
    left: 50%;
}`

with local css:

`.modal-dialog {
    left: 0;
}`

fixes it

**Comment by vygis** [comment]
I would suggest to remove the `bootstrap` dependency at some point in the future, as `ngGovUk` is a modification/superset of bootstrap. So this issue should not happen. It could be that the bootstrap versions are clashing.
