### ISSUE TITLE
Docs: broken class list in Hidden text (progressive disclosure)

### ISSUE THREAD

**Issue by nubz** [CJSCommonPlatform/ngGovUk#27]
The class list in the docs example for **Hidden text (progressive disclosure)** reads:

`<p class="main-summary&nbsp;summary" data-ng-click="isOpen = !isOpen">`

note the &nbsp; which blocks the cascade of .summary styles to the arrow span within - when the class list is fixed the arrow is no longer positioned correctly (margin bottom declaration kicks in).

This also explains why the docs example does not show a pointer cursor.

**Comment by vygis** [comment]
@nubz this is now fixed (strange how the nbsp creeped into the example)
