### ISSUE TITLE
Stacked radio buttons & Stacked checkboxes

### ISSUE THREAD

**Issue by jamesbirrellgray** [CJSCommonPlatform/ngGovUk#28]
These need to match the gov.uk style guide

http://govuk-elements.herokuapp.com/form-elements/#form-toggle-content

**Comment by vygis** [comment]
@jamesbirrellgray: i fixed this by overriding the default Bootstrap `legend` rules:

![screen shot 2016-03-31 at 17 18 40](https://cloud.githubusercontent.com/assets/2743507/14182810/00fb54f2-f765-11e5-8e73-c6c4e8132bfa.png)
