### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by azharulc** [CJSCommonPlatform/ngGovUk#3]
Add https://badge.fury.io/ badges

**Comment by vygis** [comment]
There are two bower badges present at the moment:
1. [![Bower version](https://img.shields.io/bower/v/ng-gov-uk.svg)] (https://img.shields.io/bower/v/ng-gov-uk.svg) (in readme.md)
2. [![Bower version](https://badge.fury.io/bo/ng-gov-uk.svg )] (https://badge.fury.io/bo/ng-gov-uk.svg ) https://badge.fury.io/bo/ng-gov-uk.svg (in the 'getting started' template of the docs app - at this time the bower version is broken)

Is there a reason why two sets of badges are used, and is there a preference for `fury.io`?

**Comment by jamesbirrellgray** [comment]
No prefernce to badge supplier - can we add the travis build and coverage badges as well please

**Comment by vygis** [comment]
@jamesbirrellgray I've removed the broken bower badge and added travis build badge (PR https://github.com/CJSCommonPlatform/ngGovUk/pull/61). In order to have a code version badge, we need to have an account for `CJSCommonPlatform` in [coveralls.io](https://coveralls.io)
