### ISSUE TITLE
Create a "vertical spacer" helper div class

### ISSUE THREAD

**Issue by jamesbirrellgray** [CJSCommonPlatform/ngGovUk#40]
Create a helper class that can be added to div that adds the correct vertical space between elements

eg: <div class="vertical-space"> 

not sure what the correct space should be ... trying to find the correct style guide!

**Comment by vygis** [comment]
@jamesbirrellgray maybe ` @line-height-computed` (20px - `@navbar-margin-bottom` is set to that value)?

**Comment by jamesbirrellgray** [comment]
That sounds good :-)
