### ISSUE TITLE
Page footer styling a.k.a. Page content min-height.

### ISSUE THREAD

**Issue by AntoCuc** [CJSCommonPlatform/ngGovUk#54]
On pages with little content the footer is rendered un-naturally high in the page and with no white space.

I believe a content min-height + padding/margin top would improve the User Experience.

**Comment by pabloibanezcom** [comment]
I will work on it :smile:

**Comment by pabloibanezcom** [comment]
Hi @AntoCuc ,

After creating one page with a few lines I can't see what's wrong with the footer. Could you give more details?

**Comment by PanosParalakis** [comment]
Fixed by PR #78
