### ISSUE TITLE
The div with class nav-side should be replaced with the aside tag

### ISSUE THREAD

**Issue by AntoCuc** [CJSCommonPlatform/ngGovUk#55]
The div with class nav-side should be replaced with the aside tag inline with W3C standards.

Please refer:

1. https://www.w3.org/TR/html-markup/aside.html
2. https://www.w3.org/wiki/HTML/Elements/aside

**Comment by vygis** [comment]
@AntoCuc bear in mind that we have to support IE8

**Comment by AntoCuc** [comment]
@vygis Agreed, I thought we had a shiv promoting IE8's support for the semantically valid element? 
Something along the lines of https://github.com/aFarkas/html5shiv (not endorsed)

**Comment by guidr** [comment]
@AntoCuc yes, this is supposed to work. I'll replace it and check to see the results

**Comment by guidr** [comment]
Created a pull request for this change. Also added htmlsiv script on index.html file
