### ISSUE TITLE
Styles for List of users in IdAM

### ISSUE THREAD

**Issue by akwiatek** [CJSCommonPlatform/ngGovUk#65]
Please provide style classes which would allow us to set colours in cells of a data table.
There are green, orange and grey colours needed.

<img width="1139" alt="screen shot 2016-04-12 at 10 07 27 am" src="https://cloud.githubusercontent.com/assets/16196861/14455456/86b49686-0097-11e6-91c5-a9c2baf03957.png">

**Comment by jamesbirrellgray** [comment]
This can be achieved with `.text-muted, .text-primary, .text-success, .text-info, .text-warning, and .text-danger`?

**Comment by akwiatek** [comment]
Orange colour is missing.

* .text-muted - grey OK
* .text-primary - blue
* .text-success - green OK
* .text-info - light blue
* .text-warning - old gold
* .text-danger - salmon

**Comment by PanosParalakis** [comment]
I can see that they are using different colors. I am waiting for the style guide in order to test and replace with the correct values if needed.
