### ISSUE TITLE
New Plain Notification and improving current Notifications

### ISSUE THREAD

**Issue by StefanTotev** [CJSCommonPlatform/ngGovUk#71]
I currently need to create an Invalid Notification with a link next to it. However the current Notification and its padding is about three times bigger than the link element. It has to look like:

<img width="209" alt="screen shot 2016-04-12 at 16 41 02" src="https://cloud.githubusercontent.com/assets/6977246/14466230/d016eb4a-00cd-11e6-9c7a-e91b03d543c5.png">

However, the current two elements have these paddings:

<img width="434" alt="screen shot 2016-04-12 at 16 41 14" src="https://cloud.githubusercontent.com/assets/6977246/14466273/fc2069e6-00cd-11e6-9cc9-4e372c7a0873.png">
<img width="490" alt="screen shot 2016-04-12 at 16 41 17" src="https://cloud.githubusercontent.com/assets/6977246/14466278/0077caac-00ce-11e6-913b-936d5f5dba8d.png">

I am currently using icon-notification-invalid for the Notification and btn-plain for the link. Is there a way to align the two to look like they're supposed to or is it possible to create a new type of notification (maybe icon-notification-plain) that has a transparent background and looks like a link, but has the padding and spacing of a Notification element?

Another question that I need to raise after talking with one of the UX people is can we make the Notification element wrap around the text inside? I am currently using col-sm to restrict it and simulate the effect of the notification wrapping around the text inside, but I was told that this isn't the right way of doing it and that in the future, the notification frame should wrap around the text inside.

Thanks in advance.

**Comment by PanosParalakis** [comment]
You can use the solution provided for CSS Elements > Form Elements > Input boxes & link alignement.

**Comment by StefanTotev** [comment]
That works great, thanks! But will it be possible to make the notifications wrap around the text that's inside them?

**Comment by PanosParalakis** [comment]
@StefanTotev  Can you please provide a visual so I can answer? The solution is based on different columns (divs) so no wrap by default if I have understand correctly.

**Comment by StefanTotev** [comment]
Yes, I had an issue raised for this before (https://github.com/CJSCommonPlatform/ngGovUk/issues/29) and the solution that was provided was to use columns. However, that proved to be impractical and when I spoke to the UX person on my team, he told me that the frame should wrap around the text. The visuals are in the link above for the previous issue that was raised.

**Comment by vygis** [comment]
@StefanTotev do I understand correctly that you would prefer `inline-block` behaviour for the notifications? So that the container takes up only as much space as the text contents?
![screen shot 2016-04-13 at 13 55 17](https://cloud.githubusercontent.com/assets/2743507/14493826/8bb8c7f4-017f-11e6-86c6-e3db657a64f3.png)

**Comment by StefanTotev** [comment]
@vygis Yes, that would be the prefered option. It would be great if that could be implemented.

**Comment by pabloibanezcom** [comment]
@vygis Are you working on this? Let me know if you want me to take it.

**Comment by StefanTotev** [comment]
Could the padding for the new notifications be smaller as well? The current designs that I have and that have to be implemented are like this:

<img width="257" alt="screen shot 2016-04-14 at 11 51 07" src="https://cloud.githubusercontent.com/assets/6977246/14525832/555fb704-0237-11e6-8ae6-d80ad35a7f9d.png">

I am currently using the available notifications and the spacing is too big:

<img width="544" alt="screen shot 2016-04-14 at 11 53 12" src="https://cloud.githubusercontent.com/assets/6977246/14525871/8aa80060-0237-11e6-9b35-c9e5f9c18544.png">

**Comment by PanosParalakis** [comment]
@pabloibanezcom @vygis @StefanTotev  I am working on this. The padding in the style guide is set to 30px

**Comment by PanosParalakis** [comment]
Fixed by PR #83
