### ISSUE TITLE
New notification colours

### ISSUE THREAD

**Issue by StefanTotev** [CJSCommonPlatform/ngGovUk#72]
These new notification colours would need to be added:

<img width="249" alt="screen shot 2016-04-12 at 17 40 57" src="https://cloud.githubusercontent.com/assets/6977246/14468021/e2e86e9e-00d5-11e6-9b97-21ec08ab9a5d.png">
<img width="348" alt="screen shot 2016-04-12 at 17 41 04" src="https://cloud.githubusercontent.com/assets/6977246/14468023/e419466c-00d5-11e6-9781-fec652cdb46a.png">
<img width="348" alt="screen shot 2016-04-12 at 17 41 16" src="https://cloud.githubusercontent.com/assets/6977246/14468024/e5bbd50c-00d5-11e6-9a24-88ed5874526d.png">

Thanks in advance!

**Comment by PanosParalakis** [comment]
I will create a new section "labels" under "Components", and will add missing color values. 
Colors should been global @jamesbirrellgray  is that correct?
The above colors don't seem to mach any colors in our style sheets

**Comment by StefanTotev** [comment]
These are the colours that have been provided by the UX person on my team for the IDAM screens.

**Comment by StefanTotev** [comment]
@PanosParalakis These colour details should be available in https://triadmoj.atlassian.net/wiki/display/CUE/CJS+CPP+design+redlines

**Comment by PanosParalakis** [comment]
Thats great! Thank you!
