### ISSUE TITLE
New notification component

### ISSUE THREAD

**Issue by mszygenda** [CJSCommonPlatform/ngGovUk#8]
Hello,

As discussed, we need new UI component for notifications. Please have a look at image attached.

<img width="1220" alt="screen shot 2016-02-03 at 14 59 52" src="https://cloud.githubusercontent.com/assets/135435/12785985/e4ebccac-ca86-11e5-8ebd-f023f45dd4f2.png">

**Comment by swga** [comment]
Hiy can you post the link to Larry's design as there are a couple of versions of this component (danger, warning success)

**Comment by mszygenda** [comment]
It's in this document (Page 13) (I don't think there are other versions of it though)
https://triadmoj.atlassian.net/wiki/download/attachments/41910276/IdAM_MVP_user_v5.3.4.pdf?api=v2

https://triadmoj.atlassian.net/wiki/display/IDAM/IdAM+UX

**Comment by mszygenda** [comment]
Any update on that?

**Comment by azharulc** [comment]
Working on this now

**Comment by azharulc** [comment]
if you go here http://cjscommonplatform.github.io/ngGovUk/#!/angularui

Scroll right down to the bottom, where you can get an example of the new component.

If it is what you needed, bower update to pull in the new changes

**Comment by CJSCommonPlatform** [comment]
Guys, hold off for an hour before updating, we are re-naming from Alert to Notification. Crossed wires on a naming conventions and differentiation:-)

**Comment by CJSCommonPlatform** [comment]
Just to clarify 'alerts' remain like the GDS style guide. These new styles are 'notifications'.

Az, update the class names and the docs please :-) then close the issue and let the other guys know :-)

**Comment by azharulc** [comment]
It should be right now
