### ISSUE TITLE
Alerts text not in line with the icon when there is just one line of text

### ISSUE THREAD

**Issue by LukaszKorzybski** [CJSCommonPlatform/ngGovUk#87]
![screen shot 2016-04-25 at 09 19 08](https://cloud.githubusercontent.com/assets/525768/14778035/9ee38434-0ac8-11e6-8f23-0cd78c0e45ae.png)

**Comment by blackmonday** [comment]
You may find the CJS_CPP_Panels_v1 PDF useful.
https://triadmoj.atlassian.net/wiki/display/CUE/CJS+CPP+design+redlines

**Comment by LukaszKorzybski** [comment]
FYI below is excerpt, from the document provided by Larry, that shows how it should look like:

![screen shot 2016-04-26 at 09 27 04](https://cloud.githubusercontent.com/assets/525768/14811693/2806c1c2-0b91-11e6-8604-402c0a0542cf.png)

**Comment by PanosParalakis** [comment]
This has been fixed by the new notifications code.

**Comment by LukaszKorzybski** [comment]
@PanosParalakis Thank you. Can you please provide more info ?

**Comment by PanosParalakis** [comment]
Fixed by #86
